FROM scratch
ADD https://buildlogs.centos.org/centos/7/docker/CentOS-7-20140625-x86_64-docker_01.img.tar.xz /

#LABEL org.label-schema.schema-version="1.0" \
#    org.label-schema.name="CentOS Base Image" \
#    org.label-schema.vendor="CentOS" \
#    org.label-schema.license="GPLv2" \
#    org.label-schema.build-date="20190305"

CMD ["/bin/bash"]

